package com.sudhanshu.loanmanagement.audit.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;

@Data
@Builder
@Schema(
        name = "Audit Response",
        description = "Represents an audit log entry generated by the system."
)
public class AuditResponseDto {

    @Schema(
            description = "Unique audit log identifier",
            example = "1001"
    )
    private Long auditId;

    @Schema(
            description = "Username of the user who performed the action",
            example = "admin"
    )
    private String username;

    @Schema(
            description = "Application module where the action occurred",
            example = "Loan Management"
    )
    private String module;

    @Schema(
            description = "Action performed by the user",
            example = "APPROVE_LOAN"
    )
    private String action;

    @Schema(
            description = "Detailed description of the audit event",
            example = "Loan #101 approved successfully by ADMIN."
    )
    private String description;

    @Schema(
            description = "Date and time when the audit event was recorded",
            example = "2026-08-07T15:45:30"
    )
    private LocalDateTime createdAt;

}




