ALTER TABLE customers ADD COLUMN deleted BOOLEAN DEFAULT FALSE, ADD COLUMN deleted_at DATETIME NULL;
ALTER TABLE loans ADD COLUMN deleted BOOLEAN DEFAULT FALSE, ADD COLUMN deleted_at DATETIME NULL;
ALTER TABLE users ADD COLUMN deleted BOOLEAN DEFAULT FALSE, ADD COLUMN deleted_at DATETIME NULL;